#!/bin/env python3
import click
from daqconf.cider.apps.cider_app import Cider

@click.command()
@click.option('-f', '--input-file', 'input_file', default=None, required=False)
def cider(input_file):
    
    app = Cider()
    
    if input_file is not None:
        app.set_input_file(input_file)
    
    app.run()

# Run dbe-screen
if __name__=="__main__":
    cider()