#!/bin/env python3
import click
from daqconf.randomize_connectivity_service_port import randomize_connectivity_service_port

@click.command()
@click.argument('oks_session_name')
@click.argument('oksfile')
@click.argument('specified_port', required=False, default=0)
def daqconf_randomize_connectivity_service_port(oksfile, oks_session_name, specified_port):
  """Script to set the value of the Connectivity Service port in the specified Session of the
  specified OKS database file to a random available port number"""
  randomize_connectivity_service_port(oksfile, oks_session_name, specified_port)

if __name__ == '__main__':
  daqconf_randomize_connectivity_service_port()
