#!/bin/env python3
import click
from daqconf.randomize_connectivity_service_port import randomize_connectivity_service_port

@click.command()
@click.argument('oks_session_name')
@click.argument('oksfile')
def oks_randomize_connectivity_service_port(oksfile, oks_session_name):
  """Script to set the value of the Connectivity Service port in the specified Session of the
  specified OKS database file to a random available port number"""
  randomize_connectivity_service_port(oksfile, oks_session_name)

if __name__ == '__main__':
  oks_randomize_connectivity_service_port()
