#!/bin/env python3
import click
from daqconf.jsonify import jsonify_xml_data
from daqconf.utils import log_levels, setup_logging

@click.command()
@click.option('--oksfile', '-i', help='Input database to read')
@click.option('--log-level', '-l', help='Log level', default='INFO', type=click.Choice(log_levels, case_sensitive=False))
@click.argument('output_file')
def jsonify_xml(oksfile, output_file, log_level):
    setup_logging(log_level)
    jsonify_xml_data(oksfile, output_file)

if __name__ == '__main__':
    jsonify_xml()
